### ISSUE TITLE
MT5 docker version needs an update

### ISSUE THREAD

**Issue by alihaskar** [ejtraderLabs/ejtraderMT#11]
the current build of MT5 is no longer supported by most brokers, 
you will fail to connect to any broker's server.

**Comment by traderpedroso** [comment]
> the current build of MT5 is no longer supported by most brokers,
> you will fail to connect to any broker's server.

sure I'll update this till Friday thanks to inform

**Comment by DiMiTriFrog** [comment]
> > the current build of MT5 is no longer supported by most brokers,
> > you will fail to connect to any broker's server.
> 
> sure I'll update this till Friday thanks to inform

Any news?

**Comment by traderpedroso** [comment]
Apologies, I'm currently short on time and without a Windows operating system to download the new MT5. Simply clone the repository, open MetaTrader in /portable mode, update it, and then you can proceed with the Docker build.
