### ISSUE TITLE
How get clean data and how get last candle?

### ISSUE THREAD

**Issue by DiMiTriFrog** [ejtraderLabs/ejtraderMT#12]
After long work, i compiled on  windows VPS and now is working but i'm some questions.

Could I receive clean data without loading bar ? I mean.. when i'm getting the candles avoid to print the loading bar.
<img width="952" alt="Screenshot 2023-11-20 at 00 26 15" src="https://github.com/ejtraderLabs/ejtraderMT/assets/38754548/15c517ce-a709-400a-9f0a-cb454ffd73ba">

How could get only the last candle? I tried to:

```
    symbol = "EURUSD"
    timeframe = "M15"
    fromDate =  2

    history = api.history(symbol,timeframe,fromDate)
```
[]
But getting :
<img width="617" alt="Screenshot 2023-11-20 at 00 30 11" src="https://github.com/ejtraderLabs/ejtraderMT/assets/38754548/0ac93dbc-ea5c-45d9-a401-4a736fbb2697">

And any alternative to  mt5.symbol_info(symbol) ???

**Comment by traderpedroso** [comment]
the last row is the atual price - 

```
last_row = history.iloc[-1]
print(last_row)
```
