### ISSUE TITLE
Python não comunica com o MT5

### ISSUE THREAD

**Issue by wedersonrsouza** [ejtraderLabs/ejtraderMT#3]
Estou usando o MT5 o Docker usando a sua imagem(Dockerfile) está rodando tudo bem, porem nao consigo comunicar pelo python.

![image](https://user-images.githubusercontent.com/22062123/141649763-d5a72d54-f583-4ee4-a1c0-38b090de04d7.png)

PYTHON SCRIPT:

from ejtraderMT import Metatrader

api = Metatrader()
symbol = ["PETR4"]
timeframe = "M15"
fromDate = "20/02/2021"
toDate = "24/02/2021"

history = api.history(symbol,timeframe,fromDate,toDate)
print(history)

![image](https://user-images.githubusercontent.com/22062123/141649670-76e31994-19d4-4ad5-b64b-6297fafb7ae9.png)

![image](https://user-images.githubusercontent.com/22062123/141649691-be842168-61bd-4c89-8ee5-7286e4f5efe4.png)

O que estou fazendo de errado?

**Comment by traderpedroso** [comment]
> Estou usando o MT5 o Docker usando a sua imagem(Dockerfile) está rodando tudo bem, porem nao consigo comunicar pelo python.
> 
> ![image](https://user-images.githubusercontent.com/22062123/141649763-d5a72d54-f583-4ee4-a1c0-38b090de04d7.png)
> 
> PYTHON SCRIPT:
> 
> from ejtraderMT import Metatrader
> 
> api = Metatrader() symbol = ["PETR4"] timeframe = "M15" fromDate = "20/02/2021" toDate = "24/02/2021"
> 
> history = api.history(symbol,timeframe,fromDate,toDate) print(history)
> 
> ![image](https://user-images.githubusercontent.com/22062123/141649670-76e31994-19d4-4ad5-b64b-6297fafb7ae9.png)
> 
> ![image](https://user-images.githubusercontent.com/22062123/141649691-be842168-61bd-4c89-8ee5-7286e4f5efe4.png)
> 
> O que estou fazendo de errado?

normalmente este erro esta relacionado a porta travada ou script rodando no background melhor opção reiniciar sua maquina a outra  mandar e matar script em python que esta rodando background  sudo pkill pythonscript.py claro dependendo do seu sistema operacional provavelmente você fez um request de dados de muito longo prazo e travou a fila de dados

**Comment by wedersonrsouza** [comment]
Eu reinicie tudo e realmente comunicou, porém está retornando esse erro agora:

![image](https://user-images.githubusercontent.com/22062123/141654566-d144029b-3ff2-4f2f-92dd-1ff2eab846c6.png)

![image](https://user-images.githubusercontent.com/22062123/141654596-c377cf5b-155e-4b64-800e-483ac6d50bc6.png)

**Comment by traderpedroso** [comment]
certo não cheguei testar na ultima versão do metatrader  5 mais acredito que esta com divergência da versão do ejtraderMT vou tentar reproduzir o error se estiver na versão 3.0.6 não precisa colocar chaves antes do símbolo somente quando for puxar dataframe unificado com dois símbolos  atualmente pode chamar o símbolo somente entre aspas exemplo "WIN$" de qualquer forma amanha vou atualizar a imagem do docker e um update das alterações e melhorias do código

**Comment by traderpedroso** [comment]
> Eu reinicie tudo e realmente comunicou, porém está retornando esse erro agora:
> 
> ![image](https://user-images.githubusercontent.com/22062123/141654566-d144029b-3ff2-4f2f-92dd-1ff2eab846c6.png)
> 
> ![image](https://user-images.githubusercontent.com/22062123/141654596-c377cf5b-155e-4b64-800e-483ac6d50bc6.png)


tudo funcionando perfeitamente não consegui reproduzir seu error a única coisa que consegui notar que atualmente conseguimos somente puxar um ano de dados diferente de anteriormente que era possível puxar mais de 30 anos de dados
