### ISSUE TITLE
error 5040 Damaged parameter of string type

### ISSUE THREAD

**Issue by hfont** [ejtraderLabs/ejtraderMT#4]
Hello thank you for making this api available very grateful to you.

I've been using many functions but when I call api.positions() and api.orders() I get these errors, I don't know what it is, I did a search and found this https://github.com/khramkov/MQL5-JSON-API/issues/11.

positions = api.positions()
orders = api.orders()

print(positions)
print(orders)

#output

{"error":true,"lastError":"5040","description":"Damaged parameter of string type","function":"GetPositions"}

{"error":true,"lastError":"5040","description":"Damaged parameter of string type","function":"GetPositions"}

**Comment by traderpedroso** [comment]
> Hello thank you for making this api available very grateful to you.
> 
> I've been using many functions but when I call api.positions() and api.orders() I get these errors, I don't know what it is, I did a search and found this [khramkov/MQL5-JSON-API#11](https://github.com/khramkov/MQL5-JSON-API/issues/11).
> 
> positions = api.positions() orders = api.orders()
> 
> print(positions) print(orders)
> 
> #output
> 
> {"error":true,"lastError":"5040","description":"Damaged parameter of string type","function":"GetPositions"}
> 
> {"error":true,"lastError":"5040","description":"Damaged parameter of string type","function":"GetPositions"}

Sorry for the late response, thank you will update today

**Comment by traderpedroso** [comment]
a workaround is to change Include/json.mqh @ line 203 to detect if the error state changes then ignore it by resetting.
will update the code later today
```python
int err = GetLastError();
m_iv   = StringToInteger (m_sv);
m_dv   = StringToDouble (m_sv);
if ((err == 0) && (GetLastError() != 0)) { //Ignore conversion errors if they occur
   ResetLastError();
}
```
