### ISSUE TITLE
Remove reference to symbol. 

### ISSUE THREAD

**Issue by mmgarcia** [ejtraderLabs/ejtraderMT#5]
Symbol reference causes issues when running on python 3.10.x because it was removed 
 
see there reference.

https://docs.python.org/3.9/library/symbol.html#symbol.sym_name

**Comment by traderpedroso** [comment]
> Symbol reference causes issues when running on python 3.10.x because it was removed
> 
> see there reference.
> 
> https://docs.python.org/3.9/library/symbol.html#symbol.sym_nam

I'm using version  pip install ejtraderMT==3.0.6 I guess problem is on last version 3.0.7 with calendar do you have any suggestion ?

**Comment by traderpedroso** [comment]
> Symbol reference causes issues when running on python 3.10.x because it was removed
> 
> see there reference.
> 
> https://docs.python.org/3.9/library/symbol.html#symbol.sym_name

Thank you was just the import symbol after remove is working again thank you and sorry for late response

**Comment by mmgarcia** [comment]
Hi @traderpedroso , Thanks for your response. I appreciated. I tried to play around with this project using the docker images but I couldn't find the way to send the account credentials for connecting to metatrader5 using the api connected  to docker container.  Can you please give me any idea how do it?

**Comment by traderpedroso** [comment]
> Hi @traderpedroso , Thanks for your response. I appreciated. I tried to play around with this project using the docker images but I couldn't find the way to send the account credentials for connecting to metatrader5 using the api connected to docker container. Can you please give me any idea how do it?

you need to login to vnc using user: root password: root and do normal login as you do on the local metatrader 5 the vnc is on port 5900
